version: "3.5"
services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
      # - "8080:8080"
    depends_on:
      - mariadb
      - wordpress
      # - adminer
    container_name: nginx
    restart: unless-stopped
    volumes:
      - vwp:/var/www/html
      # - adminer:/var/www/adminer
    networks:
      - 13_network

  wordpress:
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
      - redis
    image: wordpress
    container_name: wordpress
    env_file: ./.env
    restart: unless-stopped
    networks:
      - 13_network
    volumes:
      - vwp:/var/www/html

  mariadb:
    build: ./requirements/mariadb/
      # context: .
      # dockerfile: ./requirements/mariadb/Dockerfile
    image: mariadb
    env_file:
      - ./.env
    networks:
      - 13_network
    container_name: mariadb
    restart: unless-stopped
    # volumes:
    #   - vmd:/var/lib/mysql
  
  adminer:
    depends_on:
      - mariadb
    ports: 
      - "1111:1111"
    build: ./requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    restart: unless-stopped
    networks:
      - 13_network

  static_website:
    build : ./requirements/bonus/website/
    image: mywebsite
    ports:
      - "1024:1024"
    container_name: static_website
    restart: unless-stopped
    networks:
      - 13_network
  
  redis:
    build: ./requirements/bonus/redis
    image: redis
    restart: unless-stopped
    container_name: redis
    networks:
      - 13_network
  
  cadvisor:
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    ports:
      - "2020:2020"
    restart: unless-stopped
    container_name: cadvisor
    networks:
      - 13_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

volumes:
  vwp:
    driver_opts:
      type: none
      o: bind
      device: /Users/skasmi/Desktop/data/wordpress
  vmd:
    driver_opts:
      type: none
      o: bind
      device: /Users/skasmi/Desktop/data/mariadb
      
networks:
  13_network:
    driver : bridge


# my errors  
  # error naames of images : ------> fixed
  # bind && bridge
  # login website 
  # docker volume inspect 
  # error sub admin : ------> fixed
  # how to connect in data base without pass
  # error to run in port 80