version: "3.5"
services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
      # - "8080:8080"
    depends_on:
      - mariadb
      - wordpress
      # - adminer
    container_name: nginx
    restart: unless-stopped
    volumes:
      - vwp:/var/www/html
      # - adminer:/var/www/adminer
    networks:
      - mynetwork

  wordpress:
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    env_file: ./.env
    restart: unless-stopped
    networks:
      - mynetwork
    volumes:
      - vwp:/var/www/html

  mariadb:
    build: ./requirements/mariadb/
      # context: .
      # dockerfile: ./requirements/mariadb/Dockerfile
    image: mariadb
    env_file:
      - ./.env
    networks:
      - mynetwork
    container_name: mariadb
    restart: unless-stopped
    # volumes:
    #   - vmd:/var/lib/mysql
  
  adminer:
    depends_on:
      - mariadb
    ports: 
      - "1111:1111"
    build: ./requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    restart: unless-stopped
    networks:
      - mynetwork


volumes:
  vwp:
    driver_opts:
      type: none
      o: bind
      device: /Users/skasmi/Desktop/data/wordpress
  vmd:
    driver_opts:
      type: none
      o: bind
      device: /Users/skasmi/Desktop/data/mariadb
      
networks:
  mynetwork:
    driver : bridge

  # error naames of images
  # bind && bridg
  # login website 
  # docker volume inspect 
  # error sub admin
  # how to connect in data base without pass